
Create TableSpace NETFINITY DataFile 'C:\IDAT\NETFINITY' Size 150M;


Select * From v$tablespace;


Create User USER010X  Identified by "123456"
Default TableSpace NETFINITY
Temporary TableSpace TEMP
Quota unlimited on NETFINITY;


Create Role ROL_USER10X ;


Grant CONNECT, CREATE TABLE, RESOURCE, 
      ALTER ANY INDEX, ALTER ANY SEQUENCE, ALTER ANY TABLE,
      ALTER ANY TRIGGER, CREATE ANY INDEX, CREATE ANY SEQUENCE,
      CREATE ANY SYNONYM, CREATE ANY TABLE, CREATE ANY TRIGGER,
      CREATE ANY VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, 
      CREATE TRIGGER, CREATE VIEW, DROP ANY INDEX,
      DROP ANY SEQUENCE, DROP ANY TABLE, DROP ANY TRIGGER, DROP ANY VIEW,
      INSERT ANY TABLE, QUERY REWRITE, SELECT ANY TABLE,
      UNLIMITED TABLESPACE To ROL_USER10X ;
      
Grant ROL_USER10X  To USER010X;


